name: Parallel Scraper

on:
  push:
    branches:
      - assir
  pull_request:
    branches:
      - assir

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        chunk: [file1.txt]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Ruby gems
        run: |
          gem install bundler
          bundle install || gem install capybara selenium-webdriver json nokogiri

      - name: Run Scraper
        run: |
          ruby assir.rb ${{ matrix.chunk }} results.json
