
name: Parallel Scraper

on:
  push:
    branches:
      - assir
  pull_request:
    branches:
      - assir

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pageRange:
          - "2001-2200"
          - "2201-2400"
          - "2401-2600"
          - "2601-2800"
          - "2801-3000"
          - "3001-3200"
          - "3201-3400"
          - "3401-3605"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install playwright cheerio

      - name: Install browsers for Playwright
        run: npx playwright install
        
      - name: Run scraper on pages ${{ matrix.pageRange }}
        env:
          PAGE_RANGE: ${{ matrix.pageRange }}
        run: |
          IFS='-' read -r START_PAGE END_PAGE <<< "$PAGE_RANGE"
          echo "Start page: $START_PAGE, End page: $END_PAGE"

          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' node paly.js $START_PAGE $END_PAGE


      - name: Upload scraped data artifact
        uses: actions/upload-artifact@v4
        with:
          name: books-${{ matrix.pageRange }}
          path: books_${{ matrix.pageRange }}.ndjson
