name: Parallel Scraper

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        chunk: [file1.txt, file2.txt, file3.txt, file4.txt, file5.txt, file6.txt, file7.txt, file8.txt, file9.txt, file10.txt]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Install Firefox & Geckodriver
      run: |
        sudo apt update
        sudo apt install -y firefox geckodriver
        bundle install

    - name: Run Scraper
      run: ruby darsalam.rb ${{ matrix.chunk }}

    - name: Upload JSON
      uses: actions/upload-artifact@v4
      with:
        name: result-${{ matrix.chunk }}
        path: books-output-${{ matrix.chunk }}.json
