name: Parallel Scraper

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        chunk: [file34.txt, file35.txt, file36.txt, file37.txt, file38.txt, file39.txt, file40.txt, file41.txt, file42.txt, file43.txt ]  # You can add more like file2.txt, file3.txt

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Ruby gems
        run: |
          gem install bundler
          bundle install || gem install capybara selenium-webdriver json mechanize

      - name: Run Scraper
        run: ruby darsalam.rb ${{ matrix.chunk }}

      - name: Upload JSON
        uses: actions/upload-artifact@v4
        with:
          name: salam-${{ matrix.chunk }}
          path: books-output-${{ matrix.chunk }}.json
