name: Parallel Scraper

on:
  push:
    branches:
      - assir
  pull_request:
    branches:
      - assir

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        chunk: [file1.txt, file2.txt, file3.txt, file4.txt, file5.txt, file6.txt, file7.txt, file8.txt, file9.txt, file10.txt]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Ruby gems
        run: |
          gem install bundler
          bundle install || gem install capybara selenium-webdriver json nokogiri

      - name: Run Scraper
        run: |
          mkdir -p results
          ruby assir.rb ${{ matrix.chunk }}

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.chunk }}
          path: results/$(basename "${{ matrix.chunk}" .txt).json

  combine:
    runs-on: ubuntu-latest
    needs: scrape

    steps:
      - name: Download all result artifacts
        uses: actions/download-artifact@v4
        with:
          path: results

      - name: Combine JSON files
        run: |
          echo "[" > combined.json
          find results -name "*.json" -exec cat {} \; | sed '$!s/$/,/' >> combined.json
          echo "]" >> combined.json

      - name: Upload combined JSON
        uses: actions/upload-artifact@v4
        with:
          name: combined-results
          path: combined.json
